version: "3.8"
services:
  backend:
    image: backend
    ports:
      - 8081:8080
    restart: unless-stopped
    command: ["./majiup_backend"]
    network_mode: host
  frontend:
    image: frontend
    ports:
      - 5173:5173
    restart: unless-stopped
    depends_on:
      - backend
    command: ["nginx", "-g", "daemon off;"]
    network_mode: host