version: "3.8"
services:
  backend:
    image: backend
    ports:
      - 8081:8080
    restart: unless-stopped
    command: ["./majiup_backend"]
    networks:
      - default
  frontend:
    image: frontend
    ports:
      - 5173:80
    restart: unless-stopped
    depends_on:
      - backend
    command: ["nginx", "-g", "daemon off;"]
    networks:
      - default
    environment:
      - VITE_BACKEND_URL=http://backend:8081
networks:
  default:
    external:
      name: wazigate